### ISSUE TITLE
about内文章のスペースについて

### ISSUE THREAD

**Issue by EbichanOO** [FUN-AI/HP#24]
FUNAI紹介文書きましたが、表示する際文章間の余裕があまりない様に感じます。
修正するまたは修正点を教える等していただけると助かります。

**Comment by TomSuzuki** [comment]
pタグの中ですか？それとも上の段落と次の段落の間ですか？

**Comment by TomSuzuki** [comment]
縦の隙間...？横の隙間...？

**Comment by EbichanOO** [comment]
上段落と次段落の間....

**Comment by TomSuzuki** [comment]
まって、更新見たけどそこpタグじゃなくてul-li使って欲しい...

**Comment by TomSuzuki** [comment]
あとh2の前にhr入れて

**Comment by TomSuzuki** [comment]
細かい段落わけするならh3作る？

**Comment by TomSuzuki** [comment]
修正あげたけどhrちょっと変える

**Comment by EbichanOO** [comment]
ありがと～～！

**Comment by TomSuzuki** [comment]
太い線と細い線作った（h1の下だけboldにして欲しい）
